services:
  db-dev:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: atp_db
    ports:
    - "5432:5432"
    
  
  app-dev:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: atp_dev
    depends_on:
      - db-dev
    ports:
      - "8080:8000"
    environment:
    #AQUI CAMBIAMOS HOST POR EL NOMBRE DEL CONTENEDOR DE LA BASE DE DATOS POSTGRES_DEV
      DB_CONNECTION: pgsql
      DB_HOST: db-dev 
      DB_PORT: 5432
      DB_DATABASE: atp_db
      DB_USERNAME: user
      DB_PASSWORD: 1234
      APP_KEY: ${APP_KEY}
      APP_ENV: local
      APP_DEBUG: "true"
